server:
    port: 9999

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            metrics:
                enabled: true
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                - id: doctor-service
                  uri: http://localhost:8888/
                  predicates:
                      - Path=/consult/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
